server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true


database:
  logger:
    level: "all"
    stdout: true
  default:
    link: "mysql:jcrose-cmdb:o*anqRCC8wid@tcp(common-test-db.ctsksym0mj1g.ap-east-1.rds.amazonaws.com:3306)/cmdb?loc=Asia%2FShanghai"
    #link: "mysql:root:ql2252528@tcp(192.168.44.131:3306)/cmdb?loc=Asia%2FShanghai"
    debug: true
