// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "alter-lark-webhook/internal/logic/feishu"
	_ "alter-lark-webhook/internal/logic/prometheus"
)
