// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Apps is the golang structure of table apps for DAO operations like Where/Data.
type Apps struct {
	g.Meta      `orm:"table:apps, do:true"`
	ServiceId   interface{} //
	ServiceName interface{} // 服务名,需要满足k8s-ns的要求
	GitlabId    interface{} // gitlab仓库的id号,云雀平台需要使用,外键引用gitlab_projects表
	HelmChart   interface{} // helm chart的名字
	K8SCluster  interface{} // 生产环境的k8s名称,决定了服务部署到哪个k8s集群
	Namespace   interface{} // k8s的namespace信息
	Workload    interface{} // k8s workload的类型，是deployment，还是sts
	Envs        interface{} // 该服务所属的环境, json的字符串数组格式
	Labels      interface{} // json的对象格式, 应用的所有标签
}
