// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AuditLog is the golang structure of table audit_log for DAO operations like Where/Data.
type AuditLog struct {
	g.Meta       `orm:"table:audit_log, do:true"`
	TimestampMs  interface{} // 精确到毫秒的时间戳
	TraceId      interface{} // 调用链id
	Email        interface{} // 具体用户
	CreationTime *gtime.Time // 请求时间
	Url          interface{} // 请求的具体url
	Method       interface{} // http请求方法,当前都是post
	Body         interface{} // post请求的完整参数, json格式
}
