// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DeployHistory is the golang structure of table deploy_history for DAO operations like Where/Data.
type DeployHistory struct {
	g.Meta        `orm:"table:deploy_history, do:true"`
	Id            interface{} //
	WorkflowName  interface{} // workflow的name
	GitlabUrl     interface{} // gitlab的地址
	ServiceName   interface{} // 服务名
	ServiceId     interface{} // 服务ID
	K8SCluster    interface{} // 所属K8S环境
	Env           interface{} // 所属环境,qa/dev/prod/ops类似
	Branch        interface{} // 构建时的分支名
	Image         interface{} // 构建成功的镜像地址
	DeployTime    *gtime.Time // 提交构建的时间
	CommitId      interface{} // gitlab提交的ID
	CommitMessage interface{} // gitlab构建时候的提交信息
	CommitEmail   interface{} // 构建提交的email
	CommitTime    *gtime.Time // 构建的时间
	Status        interface{} // 构建的状态
	Operator      interface{} // 构建人
	Type          interface{} // 历史类型,是CI还是CD
	Result        interface{} // 构建状态,0代表成功,其他任何数值代表失败
}
