// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DoubaoRecord is the golang structure of table doubao_record for DAO operations like Where/Data.
type DoubaoRecord struct {
	g.Meta    `orm:"table:doubao_record, do:true"`
	Id        interface{} //
	Alertname interface{} //
	Message   interface{} //
	Command   interface{} //
	EndTime   *gtime.Time //
	Result    interface{} //
}
