// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GitlabProjects is the golang structure of table gitlab_projects for DAO operations like Where/Data.
type GitlabProjects struct {
	g.Meta             `orm:"table:gitlab_projects, do:true"`
	Id                 interface{} // 就是在git仓库上查看到的Project ID
	HttpUrlToRepo      interface{} // git的url地址
	Description        interface{} // 仓库描述信息
	WebhookEnabled     interface{} // 1表示允许该gitlab仓库通过webhook触发ci,0表示不允许
	WebhookBranchOrTag interface{} // 当gitlab仓库允许webhook触发ci时,再次判断分支或tag,只有在指定范围内的才允许触发,如果为空,则表示允许所有分支/tag触发
	UiMergeEnabled     interface{} // 1表示允许该gitlab仓库开启前端合并功能, 0表示不允许
	CiPipeline         interface{} // ci时使用的pipeline名称
	Developers         interface{} // commit记录中的最近5个提交者的邮箱地址
	LastCommitTime     *gtime.Time // 该gitlab仓库最后一次commit的时间
}
