// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Locks is the golang structure of table locks for DAO operations like Where/Data.
type Locks struct {
	g.Meta   `orm:"table:locks, do:true"`
	Name     interface{} // 锁的名称
	IsLocked interface{} // 锁的状态,0表示没有被锁,1表示已锁
}
