// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Nodes is the golang structure of table nodes for DAO operations like Where/Data.
type Nodes struct {
	g.Meta     `orm:"table:nodes, do:true"`
	Id         interface{} // 索引
	Name       interface{} // 主机名
	Address    interface{} // 主机地址
	Port       interface{} // 端口
	Username   interface{} // 根用户名
	Password   interface{} // 根密码
	Os         interface{} // 操作系统
	Version    interface{} // 操作系统版本
	MemorySize interface{} // 内存大小 单位MB
	DiskSize   interface{} // 磁盘大小 单位MB
	CpuSize    interface{} // CPU大小 单位核
	Department interface{} // 部门
	Business   interface{} // 业务线
}
