// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Oncall is the golang structure of table oncall for DAO operations like Where/Data.
type Oncall struct {
	g.Meta `orm:"table:oncall, do:true"`
	Date   *gtime.Time // 值班日期
	Email  interface{} // 值班人员邮箱地址
}
