// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Portal is the golang structure of table portal for DAO operations like Where/Data.
type Portal struct {
	g.Meta      `orm:"table:portal, do:true"`
	Id          interface{} //
	Url         interface{} //
	Path        interface{} //
	Title       interface{} //
	Description interface{} //
	Env         interface{} //
	Sort        interface{} //
}
