// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PrometheusReport is the golang structure of table prometheus_report for DAO operations like Where/Data.
type PrometheusReport struct {
	g.Meta      `orm:"table:prometheus_report, do:true"`
	Id          interface{} //
	Alertname   interface{} // 告警类型
	K8SCluster  interface{} // 集群名
	ItemName    interface{} // podname或者实例名
	Env         interface{} // 环境
	Level       interface{} // 告警等级
	StartTime   *gtime.Time // 开始时间
	EndTime     *gtime.Time // 结束时间
	Description interface{} // 描述
	Summary     interface{} // 概述
	Labels      interface{} // 标签
	IsResolved  interface{} // 是否解决
}
