// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// SysConfig is the golang structure of table sys_config for DAO operations like Where/Data.
type SysConfig struct {
	g.Meta    `orm:"table:sys_config, do:true"`
	Id        interface{} // 主键
	ConfigKey interface{} // 配置项名称
	ConfigVal interface{} // 配置项的值
	MarkKey   interface{} // 对应的config_key值的备注或中文名称
	MarkVal   interface{} // 对应的config_val值的备注或中文名称
}
