// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DoubaoRecordDao is the data access object for table doubao_record.
type DoubaoRecordDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns DoubaoRecordColumns // columns contains all the column names of Table for convenient usage.
}

// DoubaoRecordColumns defines and stores column names for table doubao_record.
type DoubaoRecordColumns struct {
	Id        string //
	Alertname string //
	Message   string //
	Command   string //
	EndTime   string //
	Result    string //
}

// doubaoRecordColumns holds the columns for table doubao_record.
var doubaoRecordColumns = DoubaoRecordColumns{
	Id:        "id",
	Alertname: "alertname",
	Message:   "message",
	Command:   "command",
	EndTime:   "end_time",
	Result:    "result",
}

// NewDoubaoRecordDao creates and returns a new DAO object for table data access.
func NewDoubaoRecordDao() *DoubaoRecordDao {
	return &DoubaoRecordDao{
		group:   "default",
		table:   "doubao_record",
		columns: doubaoRecordColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DoubaoRecordDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DoubaoRecordDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DoubaoRecordDao) Columns() DoubaoRecordColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DoubaoRecordDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DoubaoRecordDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DoubaoRecordDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
