// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// LocksDao is the data access object for table locks.
type LocksDao struct {
	table   string       // table is the underlying table name of the DAO.
	group   string       // group is the database configuration group name of current DAO.
	columns LocksColumns // columns contains all the column names of Table for convenient usage.
}

// LocksColumns defines and stores column names for table locks.
type LocksColumns struct {
	Name     string // 锁的名称
	IsLocked string // 锁的状态,0表示没有被锁,1表示已锁
}

// locksColumns holds the columns for table locks.
var locksColumns = LocksColumns{
	Name:     "name",
	IsLocked: "is_locked",
}

// NewLocksDao creates and returns a new DAO object for table data access.
func NewLocksDao() *LocksDao {
	return &LocksDao{
		group:   "default",
		table:   "locks",
		columns: locksColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *LocksDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *LocksDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *LocksDao) Columns() LocksColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *LocksDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *LocksDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *LocksDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
