// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IGitlab interface {
		GetProjectIDByPath(ctx context.Context, projectPath string) (int, error)
		GetUserInfoByImageUrl(ctx context.Context, imageUrl string) (map[string]string, error)
	}
)

var (
	localGitlab IGitlab
)

func Gitlab() IGitlab {
	if localGitlab == nil {
		panic("implement not found for interface IGitlab, forgot register?")
	}
	return localGitlab
}

func RegisterGitlab(i IGitlab) {
	localGitlab = i
}
