// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
)

type (
	IPrometheus interface {
		GetRawAlertInfo(ctx context.Context) (alerts []*gjson.Json, err error)
		Record(ctx context.Context, record g.Map) (bool, error)
	}
)

var (
	localPrometheus IPrometheus
)

func Prometheus() IPrometheus {
	if localPrometheus == nil {
		panic("implement not found for interface IPrometheus, forgot register?")
	}
	return localPrometheus
}

func RegisterPrometheus(i IPrometheus) {
	localPrometheus = i
}
