// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalAppsDao is internal type for wrapping internal DAO implements.
type internalAppsDao = *internal.AppsDao

// appsDao is the data access object for table apps.
// You can define custom methods on it to extend its functionality as you wish.
type appsDao struct {
	internalAppsDao
}

var (
	// Apps is globally public accessible object for table apps operations.
	Apps = appsDao{
		internal.NewAppsDao(),
	}
)

// Fill with you ideas below.
