// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalDeployHistoryDao is internal type for wrapping internal DAO implements.
type internalDeployHistoryDao = *internal.DeployHistoryDao

// deployHistoryDao is the data access object for table deploy_history.
// You can define custom methods on it to extend its functionality as you wish.
type deployHistoryDao struct {
	internalDeployHistoryDao
}

var (
	// DeployHistory is globally public accessible object for table deploy_history operations.
	DeployHistory = deployHistoryDao{
		internal.NewDeployHistoryDao(),
	}
)

// Fill with you ideas below.
