// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalDoubaoRecordDao is internal type for wrapping internal DAO implements.
type internalDoubaoRecordDao = *internal.DoubaoRecordDao

// doubaoRecordDao is the data access object for table doubao_record.
// You can define custom methods on it to extend its functionality as you wish.
type doubaoRecordDao struct {
	internalDoubaoRecordDao
}

var (
	// DoubaoRecord is globally public accessible object for table doubao_record operations.
	DoubaoRecord = doubaoRecordDao{
		internal.NewDoubaoRecordDao(),
	}
)

// Fill with you ideas below.
