// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalGitlabProjectsDao is internal type for wrapping internal DAO implements.
type internalGitlabProjectsDao = *internal.GitlabProjectsDao

// gitlabProjectsDao is the data access object for table gitlab_projects.
// You can define custom methods on it to extend its functionality as you wish.
type gitlabProjectsDao struct {
	internalGitlabProjectsDao
}

var (
	// GitlabProjects is globally public accessible object for table gitlab_projects operations.
	GitlabProjects = gitlabProjectsDao{
		internal.NewGitlabProjectsDao(),
	}
)

// Fill with you ideas below.
