// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalLocksDao is internal type for wrapping internal DAO implements.
type internalLocksDao = *internal.LocksDao

// locksDao is the data access object for table locks.
// You can define custom methods on it to extend its functionality as you wish.
type locksDao struct {
	internalLocksDao
}

var (
	// Locks is globally public accessible object for table locks operations.
	Locks = locksDao{
		internal.NewLocksDao(),
	}
)

// Fill with you ideas below.
