// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalNodesDao is internal type for wrapping internal DAO implements.
type internalNodesDao = *internal.NodesDao

// nodesDao is the data access object for table nodes.
// You can define custom methods on it to extend its functionality as you wish.
type nodesDao struct {
	internalNodesDao
}

var (
	// Nodes is globally public accessible object for table nodes operations.
	Nodes = nodesDao{
		internal.NewNodesDao(),
	}
)

// Fill with you ideas below.
