// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalOncallDao is internal type for wrapping internal DAO implements.
type internalOncallDao = *internal.OncallDao

// oncallDao is the data access object for table oncall.
// You can define custom methods on it to extend its functionality as you wish.
type oncallDao struct {
	internalOncallDao
}

var (
	// Oncall is globally public accessible object for table oncall operations.
	Oncall = oncallDao{
		internal.NewOncallDao(),
	}
)

// Fill with you ideas below.
