// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"alter-lark-webhook/internal/dao/internal"
)

// internalPortalDao is internal type for wrapping internal DAO implements.
type internalPortalDao = *internal.PortalDao

// portalDao is the data access object for table portal.
// You can define custom methods on it to extend its functionality as you wish.
type portalDao struct {
	internalPortalDao
}

var (
	// Portal is globally public accessible object for table portal operations.
	Portal = portalDao{
		internal.NewPortalDao(),
	}
)

// Fill with you ideas below.
