// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Apps is the golang structure for table apps.
type Apps struct {
	ServiceId   int    `json:"ServiceId"   description:""`                                           //
	ServiceName string `json:"ServiceName" description:"服务名,需要满足k8s-ns的要求"`                          // 服务名,需要满足k8s-ns的要求
	GitlabId    string `json:"GitlabId"    description:"gitlab仓库的id号,云雀平台需要使用,外键引用gitlab_projects表"` // gitlab仓库的id号,云雀平台需要使用,外键引用gitlab_projects表
	HelmChart   string `json:"HelmChart"   description:"helm chart的名字"`                              // helm chart的名字
	K8SCluster  string `json:"K8SCluster"  description:"生产环境的k8s名称,决定了服务部署到哪个k8s集群"`                 // 生产环境的k8s名称,决定了服务部署到哪个k8s集群
	Namespace   string `json:"Namespace"   description:"k8s的namespace信息"`                            // k8s的namespace信息
	Workload    string `json:"Workload"    description:"k8s workload的类型，是deployment，还是sts"`          // k8s workload的类型，是deployment，还是sts
	Envs        string `json:"Envs"        description:"该服务所属的环境, json的字符串数组格式"`                     // 该服务所属的环境, json的字符串数组格式
	Labels      string `json:"Labels"      description:"json的对象格式, 应用的所有标签"`                         // json的对象格式, 应用的所有标签
}
