// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AuditLog is the golang structure for table audit_log.
type AuditLog struct {
	TimestampMs  int64       `json:"TimestampMs"  description:"精确到毫秒的时间戳"`           // 精确到毫秒的时间戳
	TraceId      string      `json:"TraceId"      description:"调用链id"`               // 调用链id
	Email        string      `json:"Email"        description:"具体用户"`                // 具体用户
	CreationTime *gtime.Time `json:"CreationTime" description:"请求时间"`                // 请求时间
	Url          string      `json:"Url"          description:"请求的具体url"`            // 请求的具体url
	Method       string      `json:"Method"       description:"http请求方法,当前都是post"`   // http请求方法,当前都是post
	Body         string      `json:"Body"         description:"post请求的完整参数, json格式"` // post请求的完整参数, json格式
}
