// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
	Id       int    `json:"Id"       description:""`                   //
	PType    string `json:"PType"    description:""`                   //
	V0       string `json:"V0"       description:""`                   //
	V1       string `json:"V1"       description:""`                   //
	V2       string `json:"V2"       description:""`                   //
	V3       string `json:"V3"       description:""`                   //
	V4       string `json:"V4"       description:""`                   //
	V5       string `json:"V5"       description:""`                   //
	PostPars string `json:"PostPars" description:"post的参数, 参数鉴权的时候使用"` // post的参数, 参数鉴权的时候使用
	Summary  string `json:"Summary"  description:"接口的概要信息"`            // 接口的概要信息
}
