// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DoubaoRecord is the golang structure for table doubao_record.
type DoubaoRecord struct {
	Id        int         `json:"Id"        description:""` //
	Alertname string      `json:"Alertname" description:""` //
	Message   string      `json:"Message"   description:""` //
	Command   string      `json:"Command"   description:""` //
	EndTime   *gtime.Time `json:"EndTime"   description:""` //
	Result    string      `json:"Result"    description:""` //
}
