// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GitlabProjects is the golang structure for table gitlab_projects.
type GitlabProjects struct {
	Id                 int         `json:"Id"                 description:"就是在git仓库上查看到的Project ID"`                                                // 就是在git仓库上查看到的Project ID
	HttpUrlToRepo      string      `json:"HttpUrlToRepo"      description:"git的url地址"`                                                              // git的url地址
	Description        string      `json:"Description"        description:"仓库描述信息"`                                                                 // 仓库描述信息
	WebhookEnabled     int         `json:"WebhookEnabled"     description:"1表示允许该gitlab仓库通过webhook触发ci,0表示不允许"`                                     // 1表示允许该gitlab仓库通过webhook触发ci,0表示不允许
	WebhookBranchOrTag string      `json:"WebhookBranchOrTag" description:"当gitlab仓库允许webhook触发ci时,再次判断分支或tag,只有在指定范围内的才允许触发,如果为空,则表示允许所有分支/tag触发"` // 当gitlab仓库允许webhook触发ci时,再次判断分支或tag,只有在指定范围内的才允许触发,如果为空,则表示允许所有分支/tag触发
	UiMergeEnabled     int         `json:"UiMergeEnabled"     description:"1表示允许该gitlab仓库开启前端合并功能, 0表示不允许"`                                         // 1表示允许该gitlab仓库开启前端合并功能, 0表示不允许
	CiPipeline         string      `json:"CiPipeline"         description:"ci时使用的pipeline名称"`                                                       // ci时使用的pipeline名称
	Developers         string      `json:"Developers"         description:"commit记录中的最近5个提交者的邮箱地址"`                                                 // commit记录中的最近5个提交者的邮箱地址
	LastCommitTime     *gtime.Time `json:"LastCommitTime"     description:"该gitlab仓库最后一次commit的时间"`                                                 // 该gitlab仓库最后一次commit的时间
}
