// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Locks is the golang structure for table locks.
type Locks struct {
	Name     string `json:"Name"     description:"锁的名称"`               // 锁的名称
	IsLocked bool   `json:"IsLocked" description:"锁的状态,0表示没有被锁,1表示已锁"` // 锁的状态,0表示没有被锁,1表示已锁
}
