// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Nodes is the golang structure for table nodes.
type Nodes struct {
	Id         int    `json:"Id"         description:"索引"`        // 索引
	Name       string `json:"Name"       description:"主机名"`       // 主机名
	Address    string `json:"Address"    description:"主机地址"`      // 主机地址
	Port       int    `json:"Port"       description:"端口"`        // 端口
	Username   string `json:"Username"   description:"根用户名"`      // 根用户名
	Password   string `json:"Password"   description:"根密码"`       // 根密码
	Os         string `json:"Os"         description:"操作系统"`      // 操作系统
	Version    string `json:"Version"    description:"操作系统版本"`    // 操作系统版本
	MemorySize string `json:"MemorySize" description:"内存大小 单位MB"` // 内存大小 单位MB
	DiskSize   string `json:"DiskSize"   description:"磁盘大小 单位MB"` // 磁盘大小 单位MB
	CpuSize    string `json:"CpuSize"    description:"CPU大小 单位核"` // CPU大小 单位核
	Department string `json:"Department" description:"部门"`        // 部门
	Business   string `json:"Business"   description:"业务线"`       // 业务线
}
