// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Oncall is the golang structure for table oncall.
type Oncall struct {
	Date  *gtime.Time `json:"Date"  description:"值班日期"`     // 值班日期
	Email string      `json:"Email" description:"值班人员邮箱地址"` // 值班人员邮箱地址
}
