// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Portal is the golang structure for table portal.
type Portal struct {
	Id          int    `json:"Id"          description:""` //
	Url         string `json:"Url"         description:""` //
	Path        string `json:"Path"        description:""` //
	Title       string `json:"Title"       description:""` //
	Description string `json:"Description" description:""` //
	Env         string `json:"Env"         description:""` //
	Sort        int    `json:"Sort"        description:""` //
}
