// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SysConfig is the golang structure for table sys_config.
type SysConfig struct {
	Id        int    `json:"Id"        description:"主键"`                     // 主键
	ConfigKey string `json:"ConfigKey" description:"配置项名称"`                  // 配置项名称
	ConfigVal string `json:"ConfigVal" description:"配置项的值"`                  // 配置项的值
	MarkKey   string `json:"MarkKey"   description:"对应的config_key值的备注或中文名称"` // 对应的config_key值的备注或中文名称
	MarkVal   string `json:"MarkVal"   description:"对应的config_val值的备注或中文名称"` // 对应的config_val值的备注或中文名称
}
